import type { AchievementDefinition } from "../types";

export const defaultAchievementDefinitions = [
  {
    id: "first-established-baseline",
    key: "FIRST_ESTABLISHED_BASELINE",
    name: "Baseline Established",
    category: "MASTERY",
    description: "Established the first reliable development baseline.",
    visibility: "VISIBLE",
    evaluationPolicy: "FIRST_ESTABLISHED_BASELINE",
    major: true,
    rewardPolicy: "SMALL",
    policyVersion: "phase-3.6-achievements",
  },
  {
    id: "first-full-month",
    key: "FIRST_FULL_MONTH",
    name: "Full Month",
    category: "DISCIPLINE",
    description: "Completed a full monthly commitment evaluation.",
    visibility: "VISIBLE",
    tier: "BRONZE",
    evaluationPolicy: "FIRST_FULL_MONTH",
    major: true,
    rewardPolicy: "STANDARD",
    policyVersion: "phase-3.6-achievements",
  },
  {
    id: "first-confirmed-level-up",
    key: "FIRST_CONFIRMED_LEVEL_UP",
    name: "Level Confirmed",
    category: "MILESTONE",
    description: "Confirmed a higher demonstrated development standard.",
    visibility: "VISIBLE",
    evaluationPolicy: "FIRST_CONFIRMED_LEVEL_UP",
    major: true,
    rewardPolicy: "SMALL",
    policyVersion: "phase-3.6-achievements",
  },
  {
    id: "first-boss-completion",
    key: "FIRST_BOSS_COMPLETION",
    name: "Boss Defeated",
    category: "BOSS",
    description: "Completed the first evidence-based Boss Challenge.",
    visibility: "VISIBLE",
    evaluationPolicy: "FIRST_BOSS_COMPLETION",
    major: true,
    rewardPolicy: "SMALL",
    policyVersion: "phase-3.6-achievements",
  },
  {
    id: "recovered-previous-standard",
    key: "RECOVERED_PREVIOUS_STANDARD",
    name: "Standard Restored",
    category: "MASTERY",
    description: "Recovered a previously demonstrated standard.",
    visibility: "HIDDEN_UNTIL_EARNED",
    evaluationPolicy: "RECOVERED_PREVIOUS_STANDARD",
    major: true,
    rewardPolicy: "STANDARD",
    policyVersion: "phase-3.6-achievements",
  },
] satisfies AchievementDefinition[];
