import type { CharacterAttribute } from "@/components/dashboard/character-attributes";
import type { CharacterIdentityData } from "@/components/dashboard/dashboard-identity";
import { activityDefinitions } from "@/config/activity-definitions";
import {
  evolvePrograms,
  predefinedImprovementAreas,
} from "@/config/improvement-areas";
import { demoPersona } from "@/lib/demo/demo-persona";
import type { AchievementSnapshot } from "@/types/achievement";
import type { ActivityRecord } from "@/types/activity";
import type { BossChallenge } from "@/types/boss";
import type { ConsistencySnapshot } from "@/types/consistency";
import type { DailyExecutionSnapshot } from "@/types/daily-execution";
import type { ImprovementSnapshot } from "@/types/improvement";
import type { JourneySnapshot } from "@/types/journey";
import type { DailyQuest } from "@/types/quest";
import type { WeeklyReminderSnapshot } from "@/types/weekly-reminder";

export const demoCharacter = {
  name: demoPersona.name,
  level: demoPersona.currentLevel,
  highestLevel: demoPersona.highestLevel,
  currentXp: demoPersona.totalXp,
  levelStateLabel: "Stable",
  title: demoPersona.title,
  streakDays: 17,
  bestStreakDays: 31,
  attributes: [
    {
      key: "running",
      label: "Running",
      value: "10 km",
      context: "This week",
      progress: 67,
    },
    {
      key: "reading",
      label: "Books",
      value: "2",
      context: "Read so far",
      progress: 50,
    },
    {
      key: "training",
      label: "Workouts",
      value: "4",
      context: "Sessions this week",
      progress: 80,
    },
    {
      key: "health",
      label: "Health",
      value: "7.2h",
      context: "Avg sleep",
      progress: 86,
    },
    {
      key: "discipline",
      label: "Discipline",
      value: "17d",
      context: "Current streak",
      progress: 57,
    },
    {
      key: "career",
      label: "Career",
      value: "6",
      context: "Focus blocks",
      progress: 75,
    },
    {
      key: "social",
      label: "Social",
      value: "2",
      context: "Meetups planned",
      progress: 66,
    },
  ],
} satisfies CharacterIdentityData & { attributes: CharacterAttribute[] };

export const demoDailyQuests = [
  {
    id: "workout",
    title: "Workout",
    description: "Complete today's training",
    source: "system",
    status: "pending",
    scheduleLabel: "Daily",
    target: {
      activityKey: "workout",
      measurementType: "completion",
    },
  },
  {
    id: "reading",
    title: "Read",
    description: "30 minutes or 30 pages",
    source: "system",
    status: "pending",
    scheduleLabel: "Daily",
    target: {
      activityKey: "reading",
      measurementType: "pages",
      value: 30,
      unit: "pages",
    },
  },
  {
    id: "run",
    title: "Run",
    description: "5 km",
    source: "system",
    status: "pending",
    scheduleLabel: "Mon / Wed / Fri",
    target: {
      activityKey: "running",
      measurementType: "distance",
      value: 5,
      unit: "km",
    },
  },
  {
    id: "meditation",
      title: "Mental Training",
    description: "10 minutes",
    source: "user",
    status: "completed",
    scheduleLabel: "Weekdays",
    target: {
      activityKey: "meditation",
      measurementType: "duration",
      value: 10,
      unit: "minutes",
    },
  },
] satisfies DailyQuest[];

export const demoActivityRecords = [
  {
    id: "activity-running-under-target",
    activityKey: "running",
    activityLabel: "Running",
    measurement: {
      type: "distance",
      value: 3,
      unit: "km",
    },
    notes: "Kept the record exact even though it is under today's run target.",
    occurredAt: "2026-08-25T07:14:00.000Z",
    status: "completed",
  },
  {
    id: "activity-reading-pages",
    activityKey: "reading",
      activityLabel: "Bookaholic",
    measurement: {
      type: "pages",
      value: 35,
      unit: "pages",
    },
    occurredAt: "2026-08-25T15:40:00.000Z",
    status: "completed",
  },
] satisfies ActivityRecord[];

export const demoWeeklyReminders = {
  maxActive: 3,
  reminders: [
    {
      id: "linkedin",
      title: "Post on LinkedIn",
      enabled: true,
      completed: false,
      createdAt: "2026-08-20",
      completedAt: null,
    },
    {
      id: "friend",
      title: "Meet a friend",
      enabled: true,
      completed: false,
      createdAt: "2026-08-20",
      completedAt: null,
    },
    {
      id: "workspace",
      title: "Clean workspace",
      enabled: true,
      completed: true,
      createdAt: "2026-08-20",
      completedAt: "2026-08-27",
    },
    {
      id: "finance",
      title: "Review finances",
      enabled: false,
      completed: false,
      createdAt: "2026-08-20",
      completedAt: null,
    },
  ],
} satisfies WeeklyReminderSnapshot;

export const demoConsistency = {
  overall: {
    currentStreak: 17,
    bestStreak: 31,
    qualifiedToday: false,
  },
  activityStreaks: [
    {
      activityKey: "running",
      activityLabel: getActivityLabel("running"),
      currentStreak: 18,
      bestStreak: 47,
      status: "active",
      todayState: "completed",
      scheduleLabel: "Mon / Wed / Fri",
    },
    {
      activityKey: "reading",
      activityLabel: getActivityLabel("reading"),
      currentStreak: 31,
      bestStreak: 42,
      status: "active",
      todayState: "completed",
      scheduleLabel: "Daily",
    },
    {
      activityKey: "workout",
      activityLabel: getActivityLabel("workout"),
      currentStreak: 12,
      bestStreak: 19,
      status: "active",
      todayState: "scheduled_rest",
      scheduleLabel: "Tue / Thu scheduled rest",
    },
    {
      activityKey: "meditation",
      activityLabel: getActivityLabel("meditation"),
      currentStreak: 7,
      bestStreak: 15,
      status: "inactive",
      todayState: "inactive",
      scheduleLabel: "Weekdays",
      inactiveDays: 3,
      inactiveLimitDays: 7,
    },
    {
      activityKey: "coding",
      activityLabel: getActivityLabel("coding"),
      currentStreak: 9,
      bestStreak: 21,
      status: "active",
      todayState: "streak_freeze",
      scheduleLabel: "Daily",
    },
    {
      activityKey: "sleep",
      activityLabel: getActivityLabel("sleep"),
      currentStreak: 0,
      bestStreak: 28,
      status: "active",
      todayState: "missed",
      scheduleLabel: "Daily",
    },
  ],
  availableFreezes: 2,
  inactiveLimitDays: 7,
} satisfies ConsistencySnapshot;

export const demoDailyExecution = {
  currentTimeLabel: "9:18 PM",
  warningThresholdLabel: "5:00 PM",
  deadlineLabel: "10:00 PM",
  calendarBoundaryLabel: "12:00 AM",
  timeRemainingLabel: "42m remaining",
  alertLevel: "critical",
  deadlineState: "critical",
  automaticFreezeAvailable: true,
  items: [
    {
      id: "today-running",
      title: "Running",
      activityKey: "running",
      targetLabel: "5 km",
      actualLabel: "0 km before deadline",
      status: "pending",
      streakAtRisk: true,
      streakLabel: "18-day streak",
    },
    {
      id: "today-reading",
      title: "Bookaholic",
      activityKey: "reading",
      targetLabel: "5 pages",
      actualLabel: "24 pages",
      status: "completed",
      streakAtRisk: false,
      streakLabel: "31-day streak",
    },
    {
      id: "today-workout",
      title: "Workout",
      activityKey: "workout",
      targetLabel: "Training session",
      status: "scheduled_rest",
    },
    {
      id: "today-meditation",
      title: "Mental Training",
      activityKey: "meditation",
      targetLabel: "10 minutes",
      actualLabel: "Inactive until Aug 30",
      status: "inactive",
    },
    {
      id: "today-water",
      title: "Deep Work",
      activityKey: "water",
      targetLabel: "2.5 L",
      actualLabel: "2.5 L",
      status: "completed",
    },
    {
      id: "today-sleep-closeout-demo",
      title: "Endurance",
      activityKey: "sleep",
      targetLabel: "7.5 hours",
      actualLabel: "0 hours before deadline",
      status: "missed",
      streakAtRisk: false,
      streakLabel: "Best preserved: 28 days",
    },
  ],
  bossAlerts: [
    {
      id: "boss-offer",
      title: "Break the 5K Barrier",
      status: "offered",
      targetLabel: "8 km",
      progressLabel: "Best attempt: 6.8 / 8 km",
      deadlineLabel: "5 days remaining",
      message: "Generated from recent running performance.",
    },
    {
      id: "boss-deadline",
      title: "Finish Stronger",
      status: "accepted",
      targetLabel: "1 book",
      deadlineLabel: "2 days remaining",
      message: "Boss deadline approaching.",
    },
    {
      id: "boss-completed",
      title: "Distance Proof",
      status: "completed",
      targetLabel: "8 km",
      actualLabel: "8.4 km",
      message: "Boss defeated. Result preserved.",
    },
    {
      id: "boss-failed",
      title: "Near Miss",
      status: "failed",
      targetLabel: "8 km",
      actualLabel: "7.2 km",
      message: "Boss failed. Consequences deferred.",
    },
  ],
  reading: {
    title: "Reading reminder",
    bookTitle: "Atomic Habits",
    pagesRead: 208,
    totalPages: 320,
    pagesRemaining: 112,
    requiredToday: true,
    status: "pending",
  },
  inactiveAlerts: [
    {
      id: "inactive-started",
      title: "Inactive Mode started",
      message: "Meditation is paused with history preserved.",
      state: "started",
    },
    {
      id: "inactive-expires",
      title: "Inactive Mode",
      message: "Running returns to active status tomorrow.",
      daysRemaining: 1,
      state: "expires_tomorrow",
    },
    {
      id: "inactive-expired",
      title: "Inactive Mode expired",
      message: "The planned pause ended. Future consequences are deferred.",
      state: "expired",
    },
  ],
  notifications: [
    {
      id: "notification-critical",
      type: "deadline",
      severity: "critical",
      title: "Critical daily deadline",
      message: "1 required commitment remains before 10:00 PM.",
      createdAt: "9:18 PM",
      mandatory: true,
    },
    {
      id: "notification-streak",
      type: "streak",
      severity: "warning",
      title: "Running streak at risk",
      message: "18-day streak remains incomplete.",
      createdAt: "8:42 PM",
      mandatory: true,
    },
    {
      id: "notification-reminder",
      type: "activity",
      severity: "reminder",
      title: "2 commitments remain",
      message: "Reminder state started after 5:00 PM.",
      createdAt: "6:02 PM",
    },
    {
      id: "notification-reading",
      type: "reading",
      severity: "reminder",
      title: "Reading progress",
      message: "Atomic Habits has 112 pages remaining.",
      createdAt: "5:34 PM",
    },
    {
      id: "notification-boss",
      type: "boss",
      severity: "warning",
      title: "Boss deadline",
      message: "Finish Stronger has 2 days remaining.",
      createdAt: "Yesterday",
      mandatory: true,
    },
    {
      id: "notification-boss-complete",
      type: "boss",
      severity: "success",
      title: "Boss defeated",
      message: "Distance Proof completed at 8.4 km.",
      createdAt: "Yesterday",
    },
    {
      id: "notification-inactive",
      type: "inactive",
      severity: "critical",
      title: "Inactive Mode expiry",
      message: "Running returns to active status tomorrow.",
      createdAt: "Yesterday",
      mandatory: true,
    },
  ],
  weeklyReminders: demoWeeklyReminders,
  scenarios: [
    {
      id: "before-5",
      label: "Before 5:00 PM",
      description: "Pending work remains visible without warning escalation.",
      deadlineState: "before_warning",
    },
    {
      id: "after-5",
      label: "After 5:00 PM",
      description: "Incomplete work enters reminder state.",
      alertLevel: "reminder",
      deadlineState: "reminder",
    },
    {
      id: "evening-warning",
      label: "Evening warning",
      description: "Unresolved required work becomes more prominent.",
      alertLevel: "warning",
      deadlineState: "warning",
    },
    {
      id: "critical",
      label: "Critical",
      description: "Near 10:00 PM, unresolved work is strongest priority.",
      alertLevel: "critical",
      deadlineState: "critical",
    },
    {
      id: "completed",
      label: "Day complete",
      description: "All required commitments completed before deadline.",
      deadlineState: "complete",
    },
    {
      id: "missed",
      label: "After 10:00 PM",
      description: "One unresolved demo item is shown as missed.",
      deadlineState: "closeout",
    },
    {
      id: "rest",
      label: "Scheduled rest",
      description: "Rest is excluded from warning escalation.",
      deadlineState: "before_warning",
    },
    {
      id: "inactive",
      label: "Inactive",
      description: "Planned pause is visible but not treated as failure.",
      deadlineState: "before_warning",
    },
    {
      id: "boss",
      label: "Boss deadline",
      description: "Boss alerts remain separate from daily commitments.",
      alertLevel: "warning",
      deadlineState: "warning",
    },
    {
      id: "reading",
      label: "Reading progress",
      description: "Current book pages remaining are shown directly.",
      alertLevel: "reminder",
      deadlineState: "reminder",
    },
    {
      id: "recovery",
      label: "Book recovery",
      description: "Post-book recovery is not a missed reading day.",
      deadlineState: "before_warning",
    },
  ],
  closeout: {
    requiredCommitments: 5,
    completedCommitments: 4,
    missedCommitments: 1,
    overallEvaluationLabel: "System evaluated",
    progressionImpactLabel: "Pending progression engine",
  },
} satisfies DailyExecutionSnapshot;

export const demoJourney = {
  currentLevel: demoPersona.currentLevel,
  highestLevel: demoPersona.highestLevel,
  completedMilestoneCount: 10,
  currentMilestoneLabel: "Current Level 38 - Endurance standard",
  milestones: [
    {
      id: "level-1",
      type: "level",
      title: "Level 1",
      status: "completed",
      description: "Started the Evolve journey.",
      level: 1,
      completedAt: "Aug 1, 2026",
    },
    {
      id: "foundation-phase",
      type: "phase",
      title: "Foundation Phase",
      status: "completed",
      description: "Established the first repeatable development routines.",
      completedAt: "Aug 4, 2026",
    },
    {
      id: "first-consistency",
      type: "achievement",
      title: "7-Day Consistency",
      status: "completed",
      description: "Recognized the first sustained execution window.",
      completedAt: "Aug 8, 2026",
      reward: {
        label: "Recognition",
        detail: "Consistency marker",
      },
    },
    {
      id: "level-10",
      type: "level",
      title: "Level 10",
      status: "completed",
      description: "Reached the first visible long-term level marker.",
      level: 10,
      completedAt: "Aug 11, 2026",
    },
    {
      id: "first-major-goal",
      type: "goal",
      title: "Completed First Major Goal",
      status: "completed",
      description: "Closed a meaningful personal-development objective.",
      completedAt: "Aug 15, 2026",
    },
    {
      id: "analytics-preview",
      type: "unlock",
      title: "Basic Analytics Preview",
      status: "completed",
      description: "A presentation-only record of a future feature unlock.",
      completedAt: "Aug 18, 2026",
      reward: {
        label: "Unlock",
        detail: "Basic progress review",
      },
    },
    {
      id: "level-20",
      type: "level",
      title: "Level 20",
      status: "completed",
      description: "Completed the first major level band in demo history.",
      level: 20,
      completedAt: "Aug 21, 2026",
    },
    {
      id: "title-consistent",
      type: "title",
      title: "New Title: Consistent",
      status: "completed",
      description: "Historical title recognition supplied by demo data.",
      completedAt: "Aug 23, 2026",
      reward: {
        label: "Title",
        detail: "Consistent",
      },
    },
    {
      id: "level-24",
      type: "level",
      title: "Level 24",
      status: "completed",
      description: "Preserved historical level milestone.",
      level: 24,
      completedAt: "Aug 24, 2026",
    },
    {
      id: "level-30",
      type: "level",
      title: "Level 30",
      status: "completed",
      description: "Completed demo level milestone before the current position.",
      level: 30,
      completedAt: "Aug 25, 2026",
    },
    {
      id: "level-42-highest",
      type: "level",
      title: "Level 42 - Highest reached",
      status: "completed",
      description: "Historical highest level remains preserved.",
      level: 42,
      completedAt: "Aug 26, 2026",
    },
    {
      id: "current-level-38",
      type: "level",
      title: "Current Level 38",
      status: "current",
      description: "Current position can sit below the highest historical level.",
      level: demoPersona.currentLevel,
    },
    {
      id: "run-100-boss",
      type: "boss",
      title: "Boss: Run 100 km",
      status: "upcoming",
      description: "Major endurance milestone shown without boss mechanics.",
      reward: {
        label: "Reward preview",
        detail: "Endurance recognition",
      },
    },
    {
      id: "advanced-analytics",
      type: "unlock",
      title: "Advanced Analytics",
      status: "upcoming",
      description: "Display-only future unlock preview.",
      reward: {
        label: "Unlock",
        detail: "Advanced analytics",
      },
    },
    {
      id: "growth-phase",
      type: "phase",
      title: "Growth Phase",
      status: "upcoming",
      description: "Conceptual next development phase. Boundaries are not final.",
    },
  ],
} satisfies JourneySnapshot;

export const demoBossChallenges = [
  {
    id: "break-5k-barrier",
    title: "Break the 5K Barrier",
    description: "Complete one 8 km run.",
    activityKey: "running",
    activityLabel: getActivityLabel("running"),
    evaluationType: "single_value",
    measurement: {
      type: "distance",
      target: 8,
      unit: "km",
    },
    currentProgress: 6.8,
    status: "offered",
    deadline: "2026-09-01",
    deadlineLabel: "5 days remaining",
    generatedReason:
      "You've established a reliable running baseline. This challenge pushes beyond it.",
    evidence: [
      {
        label: "Average session",
        value: "5.1 km",
      },
      {
        label: "Recent best",
        value: "6.3 km",
      },
      {
        label: "Consistency",
        value: "Strong",
      },
      {
        label: "Observation",
        value: "5 weeks",
      },
    ],
  },
  {
    id: "finish-stronger",
    title: "Finish Stronger",
    description: "Finish one book within 10 days.",
    activityKey: "reading",
    activityLabel: getActivityLabel("reading"),
    evaluationType: "deadline",
    measurement: {
      type: "completion",
      target: 1,
      unit: "book",
    },
    currentProgress: 0,
    status: "accepted",
    deadline: "2026-09-06",
    deadlineLabel: "10 days remaining",
    generatedReason:
      "Your reading cadence is steady enough for a tighter completion window.",
    evidence: [
      {
        label: "Average pace",
        value: "1 book / 15 days",
      },
      {
        label: "Recent focus",
        value: "31-day reading streak",
      },
    ],
  },
  {
    id: "distance-proof",
    title: "Distance Proof",
    description: "Complete one 8 km run and preserve the actual result.",
    activityKey: "running",
    activityLabel: getActivityLabel("running"),
    evaluationType: "single_value",
    measurement: {
      type: "distance",
      target: 8,
      unit: "km",
    },
    currentProgress: 8.4,
    actualResult: 8.4,
    status: "completed",
    completedAt: "Aug 27, 2026",
    generatedReason: "The completed result remains available for future history.",
    evidence: [
      {
        label: "Target",
        value: "8 km",
      },
      {
        label: "Actual",
        value: "8.4 km",
      },
    ],
  },
  {
    id: "near-miss-8k",
    title: "Near Miss",
    description: "Attempt one 8 km run before the deadline.",
    activityKey: "running",
    activityLabel: getActivityLabel("running"),
    evaluationType: "single_value",
    measurement: {
      type: "distance",
      target: 8,
      unit: "km",
    },
    currentProgress: 7.2,
    status: "failed",
    deadline: "2026-08-26",
    deadlineLabel: "Deadline passed",
    generatedReason: "Failure state is shown without deciding consequences.",
    evidence: [
      {
        label: "Best attempt",
        value: "7.2 km",
      },
    ],
  },
  {
    id: "focus-week",
    title: "Focus Week",
    description: "Complete 7 hours of focused practice within 7 days.",
    activityKey: "coding",
    activityLabel: getActivityLabel("coding"),
    evaluationType: "cumulative",
    measurement: {
      type: "duration",
      target: 7,
      unit: "hours",
    },
    currentProgress: 0,
    status: "rejected",
    deadlineLabel: "Rejected before acceptance",
    generatedReason: "Rejection remains distinct from failure.",
    evidence: [
      {
        label: "Observed practice",
        value: "45 min / day",
      },
    ],
  },
] satisfies BossChallenge[];

export const demoDashboardBoss =
  demoBossChallenges.find(
    (challenge) =>
      challenge.status === "offered" || challenge.status === "accepted",
  ) ?? demoBossChallenges[0];

export const demoAchievements = {
  achievements: [
    {
      id: "level-20-reached",
      title: "Level 20 Reached",
      description: "Reached a meaningful overall progression milestone.",
      category: "milestone",
      status: "earned",
      earnedAt: "Aug 21, 2026",
      major: true,
    },
    {
      id: "consistency-1",
      title: "Consistency I",
      description: "Completed the first sustained consistency tier.",
      category: "discipline",
      status: "earned",
      tier: 1,
      tierLabel: "I",
      progress: {
        current: 7,
        target: 7,
        unit: "days",
      },
      earnedAt: "Aug 8, 2026",
      major: true,
    },
    {
      id: "consistency-2",
      title: "Consistency II",
      description: "A stronger discipline tier currently in progress.",
      category: "discipline",
      status: "in_progress",
      tier: 2,
      tierLabel: "II",
      progress: {
        current: 17,
        target: 30,
        unit: "days",
      },
      major: true,
    },
    {
      id: "runner-1",
      title: "Runner I",
      description: "Completed the first lifetime running distance tier.",
      category: "milestone",
      status: "earned",
      tier: 1,
      tierLabel: "I",
      progress: {
        current: 100,
        target: 100,
        unit: "km",
      },
      earnedAt: "Aug 13, 2026",
    },
    {
      id: "runner-2",
      title: "Runner II",
      description: "Build toward a larger lifetime running distance mark.",
      category: "lifetime",
      status: "in_progress",
      tier: 2,
      tierLabel: "II",
      progress: {
        current: 342,
        target: 500,
        unit: "km",
      },
      major: true,
    },
    {
      id: "dedicated-reader",
      title: "Dedicated Reader",
      description: "Sustained progress through multiple completed books.",
      category: "mastery",
      status: "in_progress",
      progress: {
        current: 3,
        target: 5,
        unit: "books",
      },
    },
    {
      id: "break-5k-barrier-achievement",
      title: "Break the 5K Barrier",
      description: "Defeated a running Boss Challenge with preserved actual result.",
      category: "boss",
      status: "earned",
      progress: {
        current: 8.4,
        target: 8,
        unit: "km",
      },
      earnedAt: "Aug 27, 2026",
      major: true,
    },
    {
      id: "hundred-books",
      title: "100 Books Completed",
      description: "Long-term reading history milestone.",
      category: "lifetime",
      status: "locked",
      progress: {
        current: 18,
        target: 100,
        unit: "books",
      },
      major: true,
    },
    {
      id: "hidden-discipline",
      title: "Hidden Achievement",
      description: "Continue progressing to discover this achievement.",
      category: "discipline",
      status: "locked",
      hiddenUntilEarned: true,
      major: true,
    },
  ],
  titles: [
    {
      id: "consistent-title",
      name: "Consistent",
      description: "Earned through sustained execution.",
      sourceType: "achievement",
      sourceId: "consistency-1",
      eligibility: "active",
      earnedAt: "Aug 8, 2026",
      selected: true,
    },
    {
      id: "endurance-title",
      name: "Endurance",
      description: "Earned from a Boss victory.",
      sourceType: "boss",
      sourceId: "break-5k-barrier-achievement",
      eligibility: "active",
      earnedAt: "Aug 27, 2026",
      selected: false,
    },
    {
      id: "disciplined-title",
      name: "Disciplined",
      description: "Previously earned discipline identity.",
      sourceType: "achievement",
      sourceId: "consistency-2",
      eligibility: "inactive",
      earnedAt: "May 14, 2026",
      selected: false,
    },
  ],
} satisfies AchievementSnapshot;

export const demoLatestAchievement =
  demoAchievements.achievements.find((achievement) => achievement.status === "earned");

export const demoImprovements = {
  commitmentCapacity: 5,
  inactiveLimitDays: 7,
  predefinedAreas: predefinedImprovementAreas,
  programs: evolvePrograms,
  areas: [
    {
      id: "running-core",
      title: "Running",
      description: "Build a stronger running habit.",
      activityKey: "running",
      tier: "core",
      status: "active",
      startedAt: "2026-07-01",
      source: "predefined",
      progressBehavior: "cumulative",
      measurementLabel: "Contributes to Daily Quests",
    },
    {
      id: "reading-priority",
      title: "Bookaholic",
      description: "Build consistent reading volume.",
      activityKey: "reading",
      tier: "priority",
      status: "active",
      startedAt: "2026-07-14",
      source: "predefined",
      progressBehavior: "cumulative",
      measurementLabel: "Book and page tracking",
    },
    {
      id: "strength-priority",
      title: "Strength Training",
      description: "Develop repeatable physical training.",
      activityKey: "workout",
      tier: "priority",
      status: "active",
      startedAt: "2026-08-01",
      source: "program",
      programId: "physical-foundation",
      progressBehavior: "cumulative",
      measurementLabel: "Contributes to Daily Quests",
    },
    {
      id: "coding-flexible",
      title: "Coding",
      description: "Practice focused technical work.",
      activityKey: "coding",
      tier: "flexible",
      status: "active",
      startedAt: "2026-08-07",
      source: "predefined",
      progressBehavior: "cumulative",
      measurementLabel: "Practice duration",
    },
    {
      id: "meditation-flexible",
      title: "Mental Training",
      description: "Planned pause during travel.",
      activityKey: "meditation",
      tier: "flexible",
      status: "inactive",
      startedAt: "2026-07-20",
      inactiveSince: "2026-08-25",
      source: "predefined",
      progressBehavior: "cumulative",
      measurementLabel: "Paused, history preserved",
    },
    {
      id: "healthier-custom",
      title: "Become healthier",
      description: "Broad improvement area awaiting measurement definition.",
      tier: "flexible",
      status: "inactive",
      startedAt: "2026-08-15",
      inactiveSince: "2026-08-23",
      source: "custom",
      progressBehavior: "state",
      measurementLabel: "Measurement definition pending",
    },
    {
      id: "reading-foundation-completed",
      title: "Reading Foundation",
      description: "Completed foundation period for reading consistency.",
      activityKey: "reading",
      tier: "priority",
      status: "completed",
      startedAt: "2026-05-01",
      completedAt: "2026-06-30",
      source: "program",
      programId: "career-accelerator",
      progressBehavior: "cumulative",
      measurementLabel: "Historical record",
    },
  ],
} satisfies ImprovementSnapshot;

export const demoDashboardImprovements = demoImprovements.areas.filter(
  (area) => area.status === "active",
);

function getActivityLabel(
  activityKey: ConsistencySnapshot["activityStreaks"][number]["activityKey"],
) {
  return (
    activityDefinitions.find((activity) => activity.key === activityKey)?.label ??
    activityKey
  );
}
